### PR TITLE
Fix two bug for Firefox 33

### PR DESCRIPTION
**Pull request by yfdyh000**
从Firefox 32升到33后遇到的两个兼容性bug。
一知半解、跌跌撞撞的研究和修复，供参考。
并未测试对其他版本的兼容性。

### CODE REVIEW

**Comment by miicha** [comment]
unfortunately "Fix urlbar enter hook for Fx33+" doesn't help in ff33 when trying to enter something in a new tab. for existing tabs (with a page loaded) it works

**Comment by yfdyh000** [comment]
@miicha It looks work fine for me in Fx33, both fine.
Any suspicious information in your browser console?

**Comment by AlexVallat** [comment]
I've just tried this fix (on Firefox 34.0a2 (2014-10-02)), and agree with miicha. It fixes it for existing tabs, but on blank tabs it doesn't work, has no effect. There is nothing reported in any console.

I've tried setting breakpoints to debug this, but the whole TU_hookCode mess has defeated me. Commenting out the whole TU_hookCode("gURLBar.handleCommand", block does fix it, but of course at the cost of removing those bits of TabUtils functionality entirely.

**Comment by Mr6686** [comment]
It fixes for all tabs if NoScript isn't present

**Comment by Mr6686** [comment]
I change loadURIWithFlags: function(url, flags) by loadURIWithFlags: function(url, "current", params) in noscriptBM.js in Noscript and for now it fixes for all tabs.
I will report if I've got errors with my hack.

**Comment by yfdyh000** [comment]
Thank you, @Mr6686, although I forgot about it later, and a few detours in recent...
I made a small workaround, https://github.com/yfdyh000/tabutils/releases 2015.02.16.

**Comment by yfdyh000** [comment]
Close this Pull, because it is outdated and no response.

**Pull request closed without merging**
